    etudiants {
        NUMERIC(7) code_etudiant PK "AUTO_INCREMENT"
        VARCHAR(255) nom
        VARCHAR(255) prenom
        YEAR annee_admission
        DATETIME date_naissance
        VARCHAR(6) code_programme FK
     }