    cours {
        INTEGER cours_id PK "AUTO_INCREMENT"
        VARCHAR(255) nom
        CHAR(10) sigle
        TINYINT duree "=60"
        TINYINT nombre_semaine "=15"
        NUMERIC(8) enseignant FK
    }
