

    evaluations_etudiants {
        INTEGER evaluation_id PK "FK"
        NUMERIC(7) code_etudiant PK "FK"
        DATE date_remise
        VARCHAR(255) nom_document
        NUMERIC(5) note "NUMERIC(5,2)"
     }

