    evaluations {
        INTEGER evaluation_id PK "AUTO_INCREMENT"
        INTEGER groupe_id FK 
        VARCHAR(255) nom_evaluation
        NUMERIC(5) note_max "NUMERIC(5,2)"
        DATETIME date_passage 
    }
